apiVersion: apps/v1
kind: Deployment
metadata:
  name: sosialmedia-staging
  namespace: staging
  labels:
    app: sosialmedia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sosialmedia
  template:
    metadata:
      labels:
        app: sosialmedia
    spec:
      containers:
      - name: sosial-media
        image: denlulung/sosial-media:latest
        ports:
        - containerPort: 80