kind: Service 
apiVersion: v1
metadata:
  name: sosialmedia-staging
  namespace: staging
spec:
  selector: 
    app: sosialmedia
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80 
    nodePort: 30096
  type: LoadBalancer